# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: "Release"
  #workingDirectory: '$(Build.SourcesDirectory)/qanda'

steps:
  - task: CmdLine@2
    inputs:
      script: |
        echo  '$(System.DefaultWorkingDirectory)'
        dir
        dir qand

#  - task: UseDotNet@2
#    inputs:
#      packageType: "sdk"
#      version: "5.0.100"

#- script: dotnet build --configuration $(buildConfiguration)
#    workingDirectory:$(workingDirectory)
#    displayName: 'backend build'
